(function () {
  const PRODUCTS = [
    { id: "boiler", category: "heating", brand: "Vaillant", model: "ecoTEC pure VUW 246/7-2", code: "Демо-код SOF-10482", specs: ["24 кВт", "2 контури", "конденсаційний"], price: 18990, image: "/assets/images/product-boiler.webp", fit: "Для опалення та гарячої води в будинку або квартирі. Остаточний підбір потужності й димоходу виконує інженер." },
    { id: "pump", category: "water", brand: "Grundfos", model: "ALPHA1 L 25-60 180", code: "Демо-код SOF-20517", specs: ["напір 6 м", "до 3,6 м³/год", "180 мм"], price: 2490, image: "/assets/images/product-pump.webp", fit: "Для циркуляції теплоносія у сумісних закритих системах. Перед заміною звірте монтажну довжину та робочу точку." },
    { id: "radiator", category: "heating", brand: "Korado", model: "RADIK KLASIK 22 500 × 1000", code: "Демо-код SOF-31704", specs: ["тип 22", "500 × 1000 мм", "бокове підключення"], price: 3290, image: "/assets/images/product-radiator.webp", fit: "Для водяних систем опалення. Тепловіддачу та схему підключення потрібно перевірити за проєктом приміщення." },
    { id: "heater", category: "water", brand: "Atlantic", model: "O’Pro Profi VM 080 D400-1-M", code: "Демо-код SOF-40833", specs: ["75 л", "1,5 кВт", "вертикальний"], price: 5990, image: "/assets/images/product-water-heater.webp", fit: "Для накопичення гарячої води у квартирі або будинку. Перед монтажем перевірте місце, кріплення та електроживлення." }
  ];
  const PAGES = {
    catalog: renderCatalog,
    product: renderProduct,
    solutions: renderSolutions,
    services: renderServices,
    contact: renderContact,
    delivery: () => renderArticle("Доставка й оплата", "Умови отримання замовлення", deliveryContent(), "Доставка по Україні", "Точні строки та вартість менеджер підтверджує після перевірки складу й габаритів."),
    warranty: () => renderArticle("Гарантія та сервіс", "Підтримка після покупки", warrantyContent(), "Потрібна діагностика?", "Підготуйте модель, серійний номер і документ про покупку — так ми швидше визначимо наступний крок."),
    about: renderAbout,
    faq: renderFaq,
    partnership: renderPartnership,
    privacy: () => renderLegal("Політика конфіденційності", privacyContent()),
    terms: () => renderLegal("Умови користування", termsContent()),
    returns: () => renderArticle("Обмін і повернення", "Зрозумілий порядок дій", returnsContent(), "Потрібно оформити звернення?", "Не встановлюйте та не використовуйте товар, якщо помітили невідповідність або пошкодження."),
    blog: renderBlog,
    portfolio: renderPortfolio,
    cart: renderCart,
    checkout: renderCheckout,
    favorites: renderFavorites,
    account: renderAccount
  };

  const root = document.querySelector("[data-page-root]");
  const page = document.body.dataset.page;
  if (!root || !PAGES[page]) return;
  root.innerHTML = header() + `<main id="main" class="page-main">${PAGES[page]()}</main>` + footer() + `<div class="toast" data-page-toast role="status" aria-live="polite"></div>`;
  bindGlobal();
  bindPage(page);

  function money(value) { return new Intl.NumberFormat("uk-UA").format(value) + " грн"; }
  function cart() { try { return JSON.parse(localStorage.getItem("sofievka-cart")) || {}; } catch { return {}; } }
  function saveCart(value) { localStorage.setItem("sofievka-cart", JSON.stringify(value)); updateCounts(); }
  function favorites() { try { return JSON.parse(localStorage.getItem("sofievka-favorites")) || []; } catch { return []; } }
  function saveFavorites(value) { localStorage.setItem("sofievka-favorites", JSON.stringify(value)); updateCounts(); }
  function productById(id) { return PRODUCTS.find(item => item.id === id) || PRODUCTS[1]; }
  function addToCart(id, qty = 1) { const value = cart(); value[id] = (value[id] || 0) + qty; saveCart(value); toast("Товар додано до кошика"); }
  function toggleFavorite(id) { const value = favorites(); const next = value.includes(id) ? value.filter(item => item !== id) : [...value, id]; saveFavorites(next); toast(next.includes(id) ? "Додано в обране" : "Видалено з обраного"); return next.includes(id); }
  function toast(message) { const el = document.querySelector("[data-page-toast]"); if (!el) return; el.textContent = message; el.classList.add("is-visible"); clearTimeout(window.pageToast); window.pageToast = setTimeout(() => el.classList.remove("is-visible"), 2400); }

  function header() {
    return `<a class="skip-link" href="#main">Перейти до основного вмісту</a>
      <div class="utility-bar"><div class="container utility-bar__inner"><ul><li>Доставка по Україні</li><li><a href="/delivery.html">Оплата і доставка</a></li><li><a href="/partnership.html">Для професіоналів</a></li></ul><div class="utility-bar__contact"><span>Пн-Пт 9:00-18:00</span><a href="tel:+380501234567">+38 (050) 123 45 67</a></div></div></div>
      <header class="site-header" data-page-header><div class="container site-header__inner">
        <a class="brand" href="/index.html" aria-label="Софіївка, головна"><img src="/assets/logo-sofievka-transparent.png" width="1942" height="809" alt="Софіївка"></a>
        <button class="catalog-button" type="button" data-page-menu aria-expanded="false" aria-controls="page-catalog-menu"><span class="catalog-button__mark" aria-hidden="true"><i></i><i></i><i></i></span>Каталог</button>
        <form class="search" action="/catalog.html" role="search"><label class="sr-only" for="page-search">Пошук товарів</label><input id="page-search" name="q" type="search" placeholder="Назва, бренд або код товару"><button type="submit">Знайти</button></form>
        <div class="header-actions"><a class="header-action" href="/account.html" aria-label="Профіль"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="3.5"/><path d="M5 20c.5-4 3-6 7-6s6.5 2 7 6"/></svg><span class="header-action__label">Профіль</span></a><a class="header-action" href="/favorites.html" aria-label="Обране"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l7.8-7.5a5.5 5.5 0 0 0-.2-7.9Z"/></svg><span class="header-action__label">Обране</span><span class="header-action__count" data-fav-count>0</span></a><a class="header-action" href="/cart.html" aria-label="Кошик"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 4h2l2.2 10.2a2 2 0 0 0 2 1.6h7.7a2 2 0 0 0 2-1.6L20 7H6"/><circle cx="10" cy="20" r="1"/><circle cx="18" cy="20" r="1"/></svg><span class="header-action__label">Кошик</span><span class="header-action__count" data-cart-count>0</span></a></div>
        <nav class="catalog-menu" id="page-catalog-menu" hidden aria-label="Каталог товарів"><div class="container catalog-menu__grid"><a href="/catalog.html?category=heating"><strong>Опалення</strong><span>Котли, радіатори, тепла підлога</span></a><a href="/catalog.html?category=water"><strong>Водопостачання</strong><span>Насоси, баки, фільтри</span></a><a href="/catalog.html"><strong>Сантехніка</strong><span>Труби, арматура та змішувачі</span></a><a href="/solutions.html"><strong>Клімат</strong><span>Кондиціонування та вентиляція</span></a><a href="/services.html"><strong>Монтаж і сервіс</strong><span>Від підбору до запуску</span></a><a href="/brands.html"><strong>Бренди</strong><span>Усі виробники</span></a></div></nav>
      </div></header>`;
  }

  function footer() {
    return `<footer class="footer"><div class="container footer__top"><a class="brand brand--footer" href="/index.html"><img src="/assets/logo-sofievka-transparent.png" width="1942" height="809" alt="Софіївка"></a><p>Обладнання для тепла, води та клімату з людською інженерною підтримкою.</p></div><div class="container footer__grid"><nav aria-label="Каталог у підвалі"><h2>Каталог</h2><a href="/catalog.html?category=heating">Опалення</a><a href="/catalog.html?category=water">Водопостачання</a><a href="/catalog.html">Сантехніка</a><a href="/solutions.html">Готові рішення</a></nav><nav aria-label="Сервіс у підвалі"><h2>Сервіс</h2><a href="/services.html">Монтаж і сервіс</a><a href="/delivery.html">Доставка й оплата</a><a href="/warranty.html">Гарантія</a><a href="/returns.html">Обмін і повернення</a></nav><nav aria-label="Компанія у підвалі"><h2>Компанія</h2><a href="/about.html">Про компанію</a><a href="/brands.html">Бренди</a><a href="/partnership.html">Партнерам</a><a href="/contact.html">Контакти</a></nav><div class="footer__contacts"><h2>Зв'язок</h2><a href="tel:+380501234567">+38 (050) 123 45 67</a><a href="mailto:info@sofievka.ua">info@sofievka.ua</a><p><a href="/faq.html">FAQ</a> · <a href="/blog.html">Поради</a> · <a href="/portfolio.html">Об'єкти</a></p></div></div><div class="container footer__bottom"><span>© 2026 Торговий дім «Софіївка»</span><span><a href="/privacy.html">Конфіденційність</a> · <a href="/terms.html">Умови</a></span></div></footer>`;
  }

  function crumbs(current) { return `<nav class="page-breadcrumbs" aria-label="Хлібні крихти"><a href="/index.html">Головна</a><span>/</span><span aria-current="page">${current}</span></nav>`; }
  function hero(kicker, title, lead, light = false) { return `<section class="page-hero${light ? " page-hero--light" : ""}"><div class="container">${crumbs(title)}<div class="page-hero__grid"><div><p class="page-kicker">${kicker}</p><h1>${title}</h1></div><p class="page-hero__lead">${lead}</p></div></div></section>`; }
  function productCard(product) { return `<article class="product-card" data-product-card="${product.id}"><a class="product-card__image" href="/product.html?id=${product.id}"><img src="${product.image}" width="800" height="800" loading="lazy" alt="${product.brand} ${product.model}"></a><span class="product-card__status product-card__status--demo">Демо · наявність уточнюється</span><span class="product-card__brand">${product.brand}</span><h3><a href="/product.html?id=${product.id}">${product.model}</a></h3><span class="product-card__code">${product.code}</span><ul class="product-card__specs">${product.specs.map(x => `<li>${x}</li>`).join("")}</ul><strong class="product-card__price">${money(product.price)}</strong><div class="product-card__actions"><button class="product-card__buy" type="button" data-add="${product.id}">Купити</button><button class="product-card__favorite" type="button" data-favorite="${product.id}" aria-label="Додати в обране" aria-pressed="${favorites().includes(product.id)}"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l7.8-7.5a5.5 5.5 0 0 0-.2-7.9Z"/></svg></button></div></article>`; }

  function renderCatalog() {
    return hero("Інженерний каталог", "Каталог обладнання", "Демо-асортимент показує структуру майбутнього каталогу. Ціни, наявність і технічні дані потребують синхронізації з обліковою системою.", true) + `<section class="page-section"><div class="container"><div class="category-pills" data-categories><button class="is-active" data-category="all">Усі категорії</button><button data-category="heating">Опалення</button><button data-category="water">Вода й насоси</button><button data-category="climate">Клімат</button><button data-category="plumbing">Сантехніка</button></div><div class="catalog-layout"><aside class="catalog-filter" data-filter><h2>Фільтри</h2><div class="filter-group"><strong>Бренд</strong>${[...new Set(PRODUCTS.map(x=>x.brand))].map(x=>`<label><input type="checkbox" value="${x}" data-brand-filter> ${x}</label>`).join("")}</div><div class="filter-group"><strong>Підбір</strong><p style="color:var(--text-secondary)">Не впевнені у сумісності? Збережіть коди товарів і передайте інженеру.</p></div></aside><div><button class="button button--secondary mobile-filter-button" type="button" data-filter-toggle>Фільтри</button><div class="catalog-toolbar"><p><strong data-result-count>${PRODUCTS.length}</strong> демонстраційні позиції</p><select aria-label="Сортування"><option>За популярністю</option><option>Спочатку дешевші</option><option>Спочатку дорожчі</option></select></div><div class="catalog-products" data-catalog-products>${PRODUCTS.map(productCard).join("")}</div></div></div></div></section>`;
  }

  function renderProduct() {
    const id = new URLSearchParams(location.search).get("id") || "pump"; const p = productById(id);
    return `<section class="pdp"><div class="container">${crumbs("Товар")}<div class="pdp__top"><div class="pdp__media"><img src="${p.image}" width="1000" height="1000" alt="${p.brand} ${p.model}"></div><div><span class="pdp__brand">${p.brand}</span><h1>${p.model}</h1><span class="pdp__code">${p.code}</span><div class="pdp__fit"><h2>Чи підійде для вашої системи</h2><p>${p.fit}</p></div><dl class="pdp__specs">${p.specs.map((x,i)=>`<div><dt>${["Параметр 1","Параметр 2","Параметр 3"][i]}</dt><dd>${x}</dd></div>`).join("")}</dl><div class="buy-box"><span class="buy-box__status">Демо · наявність уточнюється</span><strong class="buy-box__price">${money(p.price)}</strong><div class="buy-box__actions"><button class="button button--primary" type="button" data-add="${p.id}">Додати до кошика</button><button class="icon-button" type="button" data-favorite="${p.id}" aria-label="Додати в обране"><svg viewBox="0 0 24 24"><path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l7.8-7.5a5.5 5.5 0 0 0-.2-7.9Z"/></svg></button></div><div class="buy-box__notes"><span>Професійна перевірка сумісності перед відправленням</span><span>Умови доставки залежать від складу та габаритів</span><span>Гарантія — за документами виробника</span></div></div></div></div></div></section><section class="page-section page-section--white"><div class="container content-layout"><div class="prose"><h2>Опис і застосування</h2><p>Ця демонстраційна картка показує структуру майбутньої сторінки товару: короткий висновок про застосування, перевірені характеристики, прозорий статус наявності, документи та сумісні монтажні компоненти. Фінальні технічні тексти мають формуватися лише з офіційних даних виробника.</p><h2>Характеристики</h2><table class="spec-table"><tbody>${p.specs.map((x,i)=>`<tr><th>${["Основний параметр","Виконання","Монтажний параметр"][i]}</th><td>${x}</td></tr>`).join("")}<tr><th>Бренд</th><td>${p.brand}</td></tr></tbody></table><h2>Документація</h2><div class="doc-row"><span>Паспорт та інструкція</span><a href="/contact.html">Запросити PDF</a></div></div><aside class="aside-card"><h2>Потрібна перевірка?</h2><p>Назвіть код моделі та опишіть систему. Інженер уточнить сумісність і необхідні компоненти.</p><a class="button button--secondary" href="/contact.html">Отримати консультацію</a></aside></div></section>`;
  }

  function renderSolutions() { return hero("Готові комплектації", "Рішення для системи в цілому", "Обладнання, автоматика, арматура та монтажні матеріали розглядаються разом — до оформлення замовлення.") + `<section class="page-section"><div class="container"><div class="solution-grid"><article class="solution-card"><div class="solution-card__media"><img src="/assets/images/solution-boiler-room.webp" alt="Комплект обладнання котельні"></div><div class="solution-card__body"><h2>Опалення приватного будинку</h2><p>Котел, циркуляція, розподіл, автоматика й безпека.</p><a class="text-link" href="/contact.html">Запросити комплектацію →</a></div></article><article class="solution-card"><div class="solution-card__media"><img src="/assets/images/hero-water.webp" alt="Обладнання системи водопостачання"></div><div class="solution-card__body"><h2>Водопостачання</h2><p>Джерело, насос, автоматика, бак, фільтрація та споживачі.</p><a class="text-link" href="/contact.html">Запросити комплектацію →</a></div></article><article class="solution-card"><div class="solution-card__media"><img src="/assets/images/hero-climate.webp" alt="Обладнання кліматичної системи"></div><div class="solution-card__body"><h2>Клімат</h2><p>Обладнання, розподіл повітря, зони та керування.</p><a class="text-link" href="/contact.html">Запросити комплектацію →</a></div></article></div></div></section><section class="page-section page-section--white"><div class="container"><div class="page-heading"><h2>Як формується рішення</h2><p>Без квізів і автоматичних обіцянок: вихідні дані перевіряє спеціаліст, а результат фіксується у специфікації.</p></div><div class="process-list"><article><span>01</span><h3>Задача</h3><p>Площа, джерело, режими роботи та обмеження.</p></article><article><span>02</span><h3>Розрахунок</h3><p>Робочі параметри й технічна сумісність.</p></article><article><span>03</span><h3>Специфікація</h3><p>Основне обладнання та потрібні для монтажу позиції.</p></article><article><span>04</span><h3>Реалізація</h3><p>Доставка, монтаж, запуск і сервіс.</p></article></div></div></section>`; }

  function renderServices() { return hero("Монтаж і сервіс", "Від підбору до стабільної роботи", "Один контекст для консультації, доставки, монтажу, запуску та подальшого обслуговування.") + `<section class="page-section"><div class="container"><div class="process-list"><article><span>01</span><h3>Підбір</h3><p>Перевіряємо потужність, напір, монтажні умови й сумісність.</p></article><article><span>02</span><h3>Доставка</h3><p>Узгоджуємо склад, комплектацію, спосіб та строк отримання.</p></article><article><span>03</span><h3>Монтаж і запуск</h3><p>Обсяг робіт і відповідальність сторін фіксуємо до початку.</p></article><article><span>04</span><h3>Сервіс</h3><p>Діагностика, планове обслуговування та гарантійні звернення.</p></article></div></div></section><section class="page-section page-section--white"><div class="container"><div class="page-heading"><h2>Що підготувати для оцінки</h2><p>Чим точніші вихідні дані, тим менше ризику переробок і незапланованих витрат.</p></div><div class="info-grid"><article><img src="/assets/icons/icon-engineer.svg" alt=""><h3>Опис об'єкта</h3><p>Тип приміщення, площа, етап будівництва та бажаний результат.</p></article><article><img src="/assets/icons/icon-installation.svg" alt=""><h3>Фото або проєкт</h3><p>Існуюча система, вузли підключення та доступне місце.</p></article><article><img src="/assets/icons/icon-service.svg" alt=""><h3>Модель обладнання</h3><p>Для сервісу — шильдик, серійний номер та опис симптомів.</p></article></div></div></section><section class="page-section"><div class="container"><div class="aside-card" style="position:static;display:grid;grid-template-columns:1fr auto;gap:28px;align-items:center"><div><h2>Обговоримо ваш об'єкт</h2><p>Залиште контакти або зателефонуйте. Менеджер уточнить дані й наступний крок.</p></div><a class="button button--primary" href="/contact.html">Зв'язатися</a></div></div></section>`; }

  function renderContact() { return hero("Контакти", "Поговоріть із фахівцем", "Допоможемо знайти товар за кодом, перевірити сумісність або підготувати комплектацію.", true) + `<section class="page-section"><div class="container"><div class="contact-grid"><div><dl class="contact-details"><div><dt>Телефони</dt><dd><a href="tel:+380501234567">+38 (050) 123 45 67</a><br><a href="tel:+380671234567">+38 (067) 123 45 67</a></dd></div><div><dt>Email</dt><dd><a href="mailto:info@sofievka.ua">info@sofievka.ua</a></dd></div><div><dt>Графік</dt><dd>Пн–Пт: 9:00–18:00<br>Сб: 9:00–15:00</dd></div><div><dt>Адреса</dt><dd>м. Софіївка, вул. Соборна, 45<br>ТЦ «Софіївський», 1 поверх</dd></div></dl></div><div class="contact-map"><p class="page-kicker">Магазин і консультація</p><h2>Перед візитом уточніть наявність конкретної моделі</h2><p>Менеджер перевірить склад і підготує товар або консультацію до вашого приїзду.</p><a class="button button--primary" href="https://maps.google.com/?q=Софіївка+вул.+Соборна+45" target="_blank" rel="noreferrer">Прокласти маршрут</a></div></div></div></section>`; }

  function renderArticle(title, kicker, content, asideTitle, asideText) { return hero(kicker, title, "Практична інформація до покупки та після отримання замовлення.", true) + `<section class="page-section page-section--white"><div class="container content-layout"><article class="prose">${content}</article><aside class="aside-card"><h2>${asideTitle}</h2><p>${asideText}</p><a class="button button--secondary" href="/contact.html">Зв'язатися з нами</a><div class="link-list"><a href="/delivery.html">Доставка й оплата <span>→</span></a><a href="/warranty.html">Гарантія <span>→</span></a><a href="/returns.html">Повернення <span>→</span></a></div></aside></div></section>`; }
  function deliveryContent(){ return `<h2>Як отримати замовлення</h2><p>Доступні відправлення перевізником по Україні та самовивіз після підтвердження готовності. Спосіб отримання залежить від габаритів, ваги, складу відвантаження та особливостей конкретного обладнання.</p><h2>Підтвердження строку</h2><ol><li>Менеджер перевіряє фактичну наявність усіх позицій.</li><li>Узгоджує місце отримання та орієнтовний строк.</li><li>Для комплектів перевіряє, що замовлення можна відправити без втрати потрібних компонентів.</li></ol><h2>Оплата</h2><p>Доступні способи оплати та потребу в передоплаті менеджер повідомляє до підтвердження замовлення. Для юридичних осіб готується рахунок і комплект супровідних документів.</p><h2>Перевірка при отриманні</h2><p>Огляньте упаковку, комплектацію та відсутність видимих пошкоджень у присутності представника перевізника. Якщо є проблема, зафіксуйте її до завершення отримання та зв'яжіться з магазином.</p>`; }
  function warrantyContent(){ return `<h2>Гарантія виробника</h2><p>Гарантійний строк і умови залежать від бренду та конкретної моделі. Підставою для звернення є документ про покупку, серійний номер і дотримання вимог виробника до монтажу та експлуатації.</p><h2>Перед зверненням</h2><ul><li>Підготуйте точну назву моделі та серійний номер.</li><li>Опишіть симптом і коли він виник.</li><li>Додайте фото підключення або повідомлення на дисплеї, якщо це безпечно.</li><li>Не розбирайте обладнання самостійно.</li></ul><h2>Що відбувається далі</h2><p>Ми уточнюємо обставини, перевіряємо документи та визначаємо коректний маршрут: консультація, діагностика, авторизований сервіс або інше рішення відповідно до умов виробника.</p><h2>Монтаж має значення</h2><p>Для частини обладнання гарантія пов'язана з кваліфікованим монтажем, введенням в експлуатацію та регулярним обслуговуванням. Ці умови потрібно перевірити до встановлення.</p>`; }
  function returnsContent(){ return `<h2>До відправлення назад</h2><p>Спочатку повідомте номер замовлення, модель і причину звернення. Ми перевіримо категорію товару, стан, комплектність та документи й погодимо спосіб передачі.</p><h2>Збережіть комплектність</h2><ul><li>Товар, аксесуари, документація та заводське пакування.</li><li>Документ, що підтверджує покупку.</li><li>Відсутність слідів монтажу або використання, якщо йдеться про товар належної якості.</li></ul><h2>Пошкодження при доставці</h2><p>Огляд виконується у відділенні або при кур'єрі. Видиме пошкодження упаковки чи товару потрібно одразу зафіксувати актом перевізника та повідомити магазин.</p><h2>Важливе уточнення</h2><p>Можливість обміну або повернення залежить від стану товару, його категорії, індивідуальної комплектації та чинних норм. Фінальну процедуру підтверджує відповідальний менеджер після перевірки звернення.</p>`; }

  function renderAbout(){ return hero("Про компанію", "Інженерний магазин, а не просто вітрина", "Ми будуємо роботу навколо сумісності системи, зрозумілої комплектації та підтримки після покупки.") + `<section class="page-section"><div class="container content-layout"><article class="prose"><h2>Наш підхід</h2><p>ТД «Софіївка» працює з обладнанням для опалення, водопостачання, сантехніки та клімату. Для покупця важлива не лише окрема модель, а те, як вона працюватиме разом з іншими компонентами.</p><p>Тому ми відокремлюємо підтверджені характеристики від припущень, уточнюємо вихідні дані та формуємо комплектацію до замовлення. Там, де потрібен розрахунок або огляд об'єкта, ми прямо про це говоримо.</p><h2>Що це дає</h2><ul><li>Менше ризику несумісних покупок.</li><li>Зрозумілий перелік потрібного для монтажу.</li><li>Один контекст від консультації до сервісу.</li><li>Документація та гарантійний маршрут без зайвих обіцянок.</li></ul></article><aside class="aside-card"><h2>Потрібен підбір?</h2><p>Опишіть задачу та надішліть наявні фото або проєкт.</p><a class="button button--primary" href="/contact.html">Зв'язатися</a></aside></div></section>`; }

  function renderFaq(){ const items=[["Як перевірити сумісність товару?","Надішліть модель наявного обладнання, фото шильдика або схему системи. Для насоса важливі робоча точка й монтажна довжина, для котла — навантаження, димохід та гідравліка."],["Чи актуальні ціни та наявність на макеті?","Ні. Поточні товарні позиції позначені як демонстраційні. Перед комерційним запуском сайт має отримувати ціни й залишки з єдиного джерела даних."],["Чи можна замовити монтаж разом з обладнанням?","Так, після уточнення географії, обсягу робіт і стану об'єкта. Оцінка та межі відповідальності погоджуються до початку робіт."],["Як дізнатися строк доставки?","Менеджер перевіряє склад відвантаження, габарити та доступний спосіб перевезення, після чого підтверджує орієнтовний строк."],["Що потрібно для гарантійного звернення?","Модель, серійний номер, документ про покупку, опис симптомів і, за можливості, фото підключення або повідомлення на дисплеї."],["Працюєте з монтажниками та підприємствами?","Так. Передбачено окремий процес для специфікацій, рахунків, документів і повторних закупівель."]]; return hero("Допомога", "Часті запитання", "Короткі відповіді про підбір, доставку, монтаж і сервіс.", true)+`<section class="page-section page-section--white"><div class="container"><div class="faq-list">${items.map(([q,a])=>`<details class="faq-item"><summary>${q}</summary><p>${a}</p></details>`).join("")}</div></div></section>`; }

  function renderPartnership(){ return hero("Для професіоналів", "Закупівлі за специфікацією", "Монтажникам, проєктантам і бізнесу — швидкий пошук за кодом, документи та комплектація об'єкта.") + `<section class="page-section"><div class="container"><div class="info-grid"><article><img src="/assets/icons/icon-engineer.svg" alt=""><h2>Технічна підтримка</h2><p>Перевірка моделей, характеристик і сумісних компонентів.</p></article><article><img src="/assets/icons/icon-delivery.svg" alt=""><h2>Комплектація об'єкта</h2><p>Зведення позицій, доступності та графіка постачання.</p></article><article><img src="/assets/icons/icon-warranty.svg" alt=""><h2>Документи</h2><p>Рахунки, супровідні документи та матеріали виробника.</p></article></div></div></section><section class="page-section page-section--white"><div class="container content-layout"><article class="prose"><h2>Як почати</h2><ol><li>Надішліть реквізити та контакт відповідальної особи.</li><li>Додайте специфікацію у зручному форматі або список кодів.</li><li>Позначте об'єкт, бажаний строк і спосіб отримання.</li><li>Менеджер повернеться з перевіреною пропозицією та питаннями.</li></ol><h2>Без вигаданих “персональних цін”</h2><p>Комерційні умови залежать від бренду, обсягу, регулярності та способу оплати. Вони підтверджуються індивідуально, а не показуються як універсальна обіцянка.</p></article><aside class="aside-card"><h2>Надіслати специфікацію</h2><p>Вкажіть об'єкт у темі листа, додайте коди та кількість.</p><a class="button button--primary" href="mailto:partner@sofievka.ua?subject=Специфікація%20об'єкта">partner@sofievka.ua</a></aside></div></section>`; }

  function renderLegal(title, content){ return hero("Правова інформація", title, "Базова редакція для структури сайту. Перед комерційним запуском текст має пройти юридичну перевірку та отримати підтверджені реквізити.", true)+`<section class="page-section page-section--white"><div class="container content-layout"><article class="prose">${content}</article><aside class="aside-card"><h2>Статус документа</h2><p>Робоча редакція від 18 серпня 2026 року. Контактні й юридичні реквізити потрібно підтвердити перед прийманням замовлень.</p><a class="button button--secondary" href="/contact.html">Поставити запитання</a></aside></div></section>`; }
  function privacyContent(){ return `<h2>Які дані можуть оброблятися</h2><p>Контактні дані, зміст звернення, склад замовлення, адреса доставки, технічна інформація про пристрій та службові дані, необхідні для безпеки й роботи сайту.</p><h2>Для чого використовуються дані</h2><ul><li>Опрацювання замовлень і консультацій.</li><li>Організація доставки, оплати, гарантії та сервісу.</li><li>Виконання законних обов'язків і захист від зловживань.</li><li>Аналітика роботи сайту — лише після належного налаштування згоди.</li></ul><h2>Передача третім сторонам</h2><p>Дані можуть передаватися перевізникам, платіжним і сервісним партнерам лише в обсязі, потрібному для відповідної послуги та за наявності правової підстави.</p><h2>Ваші права</h2><p>Ви можете звернутися щодо доступу, уточнення або видалення даних у межах, дозволених законодавством та обов'язками продавця.</p>`; }
  function termsContent(){ return `<h2>Призначення сайту</h2><p>Сайт надає інформацію про асортимент, послуги та способи зв'язку. Демонстраційні ціни й залишки не є підтвердженою комерційною пропозицією до підключення облікової системи.</p><h2>Технічна інформація</h2><p>Характеристики мають звірятися з офіційною документацією конкретної моделі. Онлайн-опис не замінює проєкт, розрахунок або інструкцію з монтажу.</p><h2>Оформлення замовлення</h2><p>Замовлення вважається погодженим після перевірки наявності, ціни, комплектації, способу оплати й доставки та підтвердження менеджером.</p><h2>Інтелектуальна власність</h2><p>Назви брендів і товарні знаки належать їхнім правовласникам. Матеріали сайту не можна відтворювати поза межами, дозволеними законом або окремою згодою.</p>`; }

  function renderBlog(){ const cards=[["Підбір","Що підготувати для підбору циркуляційного насоса","Монтажна довжина, робоча точка, тип системи й режим керування — мінімум даних для змістовної консультації."],["Опалення","Чому потужність котла — не єдиний критерій","Димохід, гідравліка, гаряча вода, автоматика та умови сервісу впливають на остаточне рішення."],["Експлуатація","Як прийняти технічне обладнання у перевізника","Перевірка упаковки, моделі, комплектності та фіксація пошкоджень до завершення отримання."]]; return hero("Практичні матеріали","Корисно знати","Короткі технічні пояснення без підміни проєктування та інструкцій виробника.",true)+`<section class="page-section"><div class="container"><div class="article-grid">${cards.map(([k,t,d])=>`<article class="editorial-card"><span>${k}</span><div><h2>${t}</h2><p>${d}</p></div></article>`).join("")}</div><p class="notice" style="margin-top:32px">Повні статті будуть опубліковані після технічної та редакційної перевірки.</p></div></section>`; }
  function renderPortfolio(){ return hero("Реалізовані об'єкти","Рішення, які можна перевірити","Ми не публікуємо вигадані кейси. Тут з'являться підтверджені об'єкти з фотографіями, складом системи та межами виконаних робіт.") + `<section class="page-section"><div class="container"><div class="portfolio-grid"><article class="editorial-card"><span>Формат кейсу</span><div><h2>Вихідна задача</h2><p>Тип об'єкта, обмеження та критерії, за якими обиралося рішення.</p></div></article><article class="editorial-card"><span>Формат кейсу</span><div><h2>Склад системи</h2><p>Перевірені моделі, ключові вузли та монтажні матеріали без рекламного перебільшення.</p></div></article><article class="editorial-card"><span>Формат кейсу</span><div><h2>Результат і сервіс</h2><p>Фактичний обсяг робіт, запуск, документація та подальше обслуговування.</p></div></article></div><div class="empty-state" style="margin-top:32px"><h2>Готуємо перші підтверджені кейси</h2><p>Фото й результати будуть додані після дозволу замовників та технічної перевірки описів.</p><a class="button button--secondary" href="/solutions.html">Переглянути напрями рішень</a></div></div></section>`; }

  function renderCart(){ const value=cart(); const lines=Object.entries(value).filter(([,q])=>q>0); return hero("Кошик","Ваше замовлення","Перевірте моделі, кількість і монтажні параметри перед оформленням.",true)+`<section class="page-section"><div class="container" data-cart-view>${cartMarkup(lines)}</div></section>`; }
  function cartMarkup(lines){ if(!lines.length) return `<div class="empty-state"><h2>Кошик порожній</h2><p>Додайте демонстраційний товар з каталогу, щоб перевірити сценарій оформлення.</p><a class="button button--primary" href="/catalog.html">До каталогу</a></div>`; const total=lines.reduce((sum,[id,q])=>sum+productById(id).price*q,0); return `<div class="cart-layout"><div class="cart-items">${lines.map(([id,q])=>{const p=productById(id);return `<article class="cart-item"><a class="cart-item__image" href="/product.html?id=${id}"><img src="${p.image}" alt="${p.brand} ${p.model}"></a><div><h2><a href="/product.html?id=${id}">${p.brand} ${p.model}</a></h2><p>${p.code}</p><div class="cart-item__controls"><button data-qty="${id}" data-delta="-1" aria-label="Зменшити">−</button><output>${q}</output><button data-qty="${id}" data-delta="1" aria-label="Збільшити">+</button></div></div><div class="cart-item__price"><strong>${money(p.price*q)}</strong><button class="cart-item__remove" data-remove="${id}">Видалити</button></div></article>`}).join("")}</div><aside class="order-summary"><h2>Разом</h2><dl><div><dt>Товари</dt><dd>${money(total)}</dd></div><div><dt>Доставка</dt><dd>після уточнення</dd></div><div class="order-summary__total"><dt>До оплати</dt><dd>${money(total)}</dd></div></dl><a class="button button--primary" href="/checkout.html">Перейти до оформлення</a></aside></div>`; }

  function renderCheckout(){ const value=cart(); const lines=Object.entries(value).filter(([,q])=>q>0); const total=lines.reduce((s,[id,q])=>s+productById(id).price*q,0); return hero("Оформлення","Контакти, доставка, оплата","Демонстраційна форма показує майбутню структуру. Вона не передає та не зберігає персональні дані.",true)+`<section class="page-section"><div class="container checkout-layout"><form class="checkout-form" data-checkout><div class="notice">Це інтерактивний макет. Замовлення не буде створено, а оплата не виконується.</div><section class="form-section"><h2>1. Контактні дані</h2><div class="form-grid"><label class="field"><span>Ім'я</span><input name="name" autocomplete="name" required></label><label class="field"><span>Телефон</span><input name="phone" type="tel" autocomplete="tel" required placeholder="+38 (___) ___ __ __"></label><label class="field field--full"><span>Email</span><input name="email" type="email" autocomplete="email"></label></div></section><section class="form-section"><h2>2. Доставка</h2><div class="choice-list"><label class="choice"><input type="radio" name="delivery" value="carrier" checked><span><strong>Перевізник по Україні</strong><small>Місто й відділення уточнюються після підключення сервісу доставки.</small></span></label><label class="choice"><input type="radio" name="delivery" value="pickup"><span><strong>Самовивіз</strong><small>Після підтвердження готовності замовлення.</small></span></label></div></section><section class="form-section"><h2>3. Оплата</h2><div class="choice-list"><label class="choice"><input type="radio" name="payment" value="confirm" checked><span><strong>Після підтвердження менеджером</strong><small>Доступний спосіб залежить від товару та доставки.</small></span></label></div><label class="field" style="margin-top:18px"><span>Коментар</span><textarea name="comment" placeholder="Питання щодо сумісності, доставки або документів"></textarea></label></section><button class="button button--primary" type="submit">Перевірити оформлення</button></form><aside class="order-summary"><h2>Ваше замовлення</h2><dl>${lines.length?lines.map(([id,q])=>{const p=productById(id);return `<div><dt>${p.brand} · ${q} шт.</dt><dd>${money(p.price*q)}</dd></div>`}).join(""):`<div><dt>Кошик</dt><dd>порожній</dd></div>`}<div class="order-summary__total"><dt>Разом</dt><dd>${money(total)}</dd></div></dl><a href="/cart.html">← Повернутися до кошика</a></aside></div></section>`; }
  function renderFavorites(){ const ids=favorites(); return hero("Збережене","Обрані товари","Зберігайте моделі для порівняння або майбутньої консультації.",true)+`<section class="page-section"><div class="container">${ids.length?`<div class="catalog-products">${ids.map(id=>productCard(productById(id))).join("")}</div>`:`<div class="empty-state"><h2>Поки нічого не збережено</h2><p>Позначте серцем потрібні товари — вони з'являться тут.</p><a class="button button--primary" href="/catalog.html">Перейти до каталогу</a></div>`}</div></section>`; }
  function renderAccount(){ return hero("Профіль","Особистий кабінет","Майбутнє місце для замовлень, збережених специфікацій і сервісних звернень.",true)+`<section class="page-section"><div class="container content-layout"><form class="aside-card" style="position:static" data-account><h2>Увійти</h2><p>Авторизація ще не підключена. Форма працює лише як візуальний сценарій.</p><label class="field" style="margin-top:22px"><span>Email або телефон</span><input required></label><label class="field" style="margin-top:14px"><span>Пароль</span><input type="password" required></label><button class="button button--primary" type="submit">Продовжити</button></form><div class="prose"><h2>Для приватних клієнтів</h2><p>Історія замовлень, гарантійні документи, адреси доставки та збережені комплекти.</p><h2>Для професіоналів</h2><p>Об'єкти, специфікації, повторне замовлення за кодами й доступ до погоджених документів.</p></div></div></section>`; }

  function bindGlobal(){ const toggle=document.querySelector("[data-page-menu]"); const menu=document.querySelector("#page-catalog-menu"); toggle?.addEventListener("click",()=>{const open=menu.hidden;menu.hidden=!open;toggle.setAttribute("aria-expanded",String(open));}); document.addEventListener("click",e=>{if(menu&&!menu.hidden&&!e.target.closest("[data-page-header]")){menu.hidden=true;toggle?.setAttribute("aria-expanded","false");}}); document.addEventListener("keydown",e=>{if(e.key==="Escape"&&menu){menu.hidden=true;toggle?.setAttribute("aria-expanded","false");}}); document.addEventListener("click",e=>{const add=e.target.closest("[data-add]"); if(add) addToCart(add.dataset.add); const fav=e.target.closest("[data-favorite]"); if(fav){const active=toggleFavorite(fav.dataset.favorite);fav.classList.toggle("is-active",active);fav.setAttribute("aria-pressed",String(active));}}); updateCounts(); }
  function updateCounts(){ const cartCount=Object.values(cart()).reduce((s,q)=>s+q,0); document.querySelectorAll("[data-cart-count]").forEach(x=>x.textContent=cartCount); document.querySelectorAll("[data-fav-count]").forEach(x=>x.textContent=favorites().length); }
  function bindPage(name){ if(name==="catalog"){const params=new URLSearchParams(location.search);let category=params.get("category")||"all";const query=(params.get("q")||"").toLocaleLowerCase("uk");const pills=[...document.querySelectorAll("[data-category]")];const render=()=>{const brands=[...document.querySelectorAll("[data-brand-filter]:checked")].map(x=>x.value);const result=PRODUCTS.filter(p=>(category==="all"||p.category===category)&&(!brands.length||brands.includes(p.brand))&&(!query||`${p.brand} ${p.model} ${p.code}`.toLocaleLowerCase("uk").includes(query)));document.querySelector("[data-catalog-products]").innerHTML=result.length?result.map(productCard).join(""):`<div class="catalog-empty"><h2>Нічого не знайдено</h2><p>Спробуйте іншу категорію або очистіть фільтри.</p></div>`;document.querySelector("[data-result-count]").textContent=result.length;pills.forEach(b=>b.classList.toggle("is-active",b.dataset.category===category));};pills.forEach(b=>b.addEventListener("click",()=>{category=b.dataset.category;render();}));document.querySelectorAll("[data-brand-filter]").forEach(x=>x.addEventListener("change",render));document.querySelector("[data-filter-toggle]")?.addEventListener("click",()=>document.querySelector("[data-filter]")?.classList.toggle("is-open"));render();}
    if(name==="cart") document.querySelector("[data-cart-view]")?.addEventListener("click",e=>{const q=e.target.closest("[data-qty]");const r=e.target.closest("[data-remove]");const value=cart();if(q)value[q.dataset.qty]=Math.max(0,(value[q.dataset.qty]||0)+Number(q.dataset.delta));if(r)delete value[r.dataset.remove];if(q||r){saveCart(value);const lines=Object.entries(value).filter(([,n])=>n>0);document.querySelector("[data-cart-view]").innerHTML=cartMarkup(lines);}});
    document.querySelector("[data-checkout]")?.addEventListener("submit",e=>{e.preventDefault();toast("Форма перевірена. Передача замовлення буде підключена окремо.");});document.querySelector("[data-account]")?.addEventListener("submit",e=>{e.preventDefault();toast("Авторизація ще не підключена");}); }
})();
