(function () {
  "use strict";

  const define = (id, definition) => Object.freeze({
    id,
    type: "select",
    unit: "",
    aliases: Object.freeze([]),
    options: null,
    filterable: true,
    sortable: false,
    categoryScope: Object.freeze([]),
    rank: 100,
    ...definition,
    aliases: Object.freeze([...(definition.aliases || [])]),
    categoryScope: Object.freeze([...(definition.categoryScope || [])])
  });

  const definitions = Object.freeze({
    productType: define("productType", { label: "Тип обладнання", rank: 1, aliases: [/^тип обладнання$/i, /^тип продукту$/i, /^категорія$/i] }),
    purpose: define("purpose", { label: "Призначення", rank: 2, aliases: [/^призначення$/i, /^застосування$/i] }),
    type: define("type", { label: "Тип", rank: 3, aliases: [/^тип$/i, /^виконання$/i] }),
    technology: define("technology", { label: "Технологія очищення", rank: 4, aliases: [/^технологія(?: очищення)?$/i, /^технология$/i] }),
    waterSource: define("waterSource", { label: "Джерело води", rank: 5, aliases: [/^джерело води$/i] }),
    installation: define("installation", { label: "Монтаж", rank: 6, aliases: [/^монтаж$/i, /^встановлення$/i, /^спосіб встановлення$/i] }),
    capacityLh: define("capacityLh", { label: "Продуктивність, л/год", type: "number", unit: "л/год", rank: 7, aliases: [/^продуктивність(?:,?\s*л\/год)?$/i] }),
    flowM3h: define("flowM3h", { label: "Продуктивність, м³/год", type: "number", unit: "м³/год", rank: 8, aliases: [/^qmax$/i, /^gmax$/i, /^макс\.?\s*продуктивність$/i, /^максимальна витрата$/i, /^витрата$/i, /^пропускна здатність(?:\s*\(м[³3]\/год\))?$/i, /^швидкість потоку(?:\s*\(м[³3]\/год\))?$/i, /^номінальна витрата$/i] }),
    capacityKgh: define("capacityKgh", { label: "Продуктивність, кг/год", type: "number", unit: "кг/год", rank: 8.1, aliases: [/^продуктивність(?:,?\s*кг\/год)?$/i, /^продуктивність.*кг\/год$/i] }),
    rotationRpm: define("rotationRpm", { label: "Частота обертання, об/хв", type: "number", unit: "об/хв", rank: 8.2, aliases: [/^частота обертання$/i, /^оберти двигуна$/i] }),
    kvs: define("kvs", { label: "Kvs, м³/год", type: "number", unit: "м³/год", rank: 9, aliases: [/^kvs(?:\s*\(.+\))?$/i, /^kv$/i] }),
    headM: define("headM", { semanticId: "maxHeadM", label: "Максимальний напір, м", type: "number", unit: "м", rank: 9, aliases: [/^hmax$/i, /^макс\.?\s*напір$/i, /^максимальний напір$/i, /^висота підйому$/i] }),
    powerKw: define("powerKw", { label: "Потужність, кВт", type: "number", unit: "кВт", rank: 10, aliases: [/^потужність$/i, /^споживана потужність$/i, /^макс\.?\s*споживана потужність$/i, /^мощность$/i] }),
    heatOutputKw: define("heatOutputKw", { label: "Теплова потужність, кВт", type: "number", unit: "кВт", rank: 11, aliases: [/^теплова потужність$/i, /^потужність макс\./i, /^qmax:.*(?:20|10)/i] }),
    fuel: define("fuel", { label: "Паливо", rank: 11.1, aliases: [/^паливо$/i, /^вид палива$/i, /^основне паливо$/i] }),
    efficiencyPercent: define("efficiencyPercent", { label: "ККД, %", type: "number", unit: "%", rank: 11.2, aliases: [/^ккд/i, /^коефіцієнт корисної дії/i] }),
    waterVolumeL: define("waterVolumeL", { label: "Водяна ємність, л", type: "number", unit: "л", rank: 11.3, aliases: [/^водяна ємність котла/i, /^об[’'`]?єм води/i] }),
    fireboxVolumeL: define("fireboxVolumeL", { label: "Об’єм топки, л", type: "number", unit: "л", rank: 11.4, aliases: [/^об[’'`]?єм топки/i, /^топка:\s*об[’'`]?єм/i] }),
    chimneyDiameterMm: define("chimneyDiameterMm", { label: "Діаметр димоходу, мм", type: "number", unit: "мм", rank: 11.5, aliases: [/^діаметр димоходу/i, /^приєднувальні розміри димоходу/i, /^рекомендовані параметри димоходу:\s*внутрішній діаметр/i] }),
    chimneyHeightM: define("chimneyHeightM", { label: "Мінімальна висота димоходу, м", type: "number", unit: "м", rank: 11.6, aliases: [/^мінімальна висота димоходу/i, /^рекомендовані параметри димоходу:\s*висота/i] }),
    consumptionPowerW: define("consumptionPowerW", { label: "Споживання електроенергії, Вт", type: "number", unit: "Вт", rank: 11.7, aliases: [/^споживання електроенергії/i, /^електрична потужність/i] }),
    maxWaterTemperatureC: define("maxWaterTemperatureC", { label: "Максимальна температура води, °C", type: "number", unit: "°C", rank: 11.8, aliases: [/^максимальна температура води/i, /^макс\.? температура теплоносія/i] }),
    mountingLengthMm: define("mountingLengthMm", { semanticId: "installationLengthMm", label: "Монтажна довжина, мм", type: "number", unit: "мм", rank: 12, aliases: [/^довжина насоса$/i, /^монтажна довжина$/i, /^будівельна довжина$/i] }),
    diameterMm: define("diameterMm", { label: "Діаметр, мм", type: "number", unit: "мм", rank: 13, aliases: [/^d\s*\(?мм\)?$/i, /^d\s*\(?mm\)?$/i, /^діаметр,?\s*мм$/i, /^диаметр,?\s*мм$/i] }),
    widthMm: define("widthMm", { label: "Ширина, мм", type: "number", unit: "мм", rank: 14, filterable: false, aliases: [/^ширина(?:\s*\(мм\))?$/i, /^w\s*\(?mm\)?$/i] }),
    heightMm: define("heightMm", { label: "Висота, мм", type: "number", unit: "мм", rank: 15, filterable: false, aliases: [/^висота(?:\s*\(мм\))?$/i, /^h\s*\(?mm\)?$/i, /^h\s*\(?мм\)?$/i] }),
    depthMm: define("depthMm", { label: "Глибина, мм", type: "number", unit: "мм", rank: 16, filterable: false, aliases: [/^глибина(?:\s*\(мм\))?$/i, /^глубина(?:\s*\(мм\))?$/i] }),
    dimensions: define("dimensions", { label: "Габарити", rank: 16.5, filterable: false, aliases: [/^розмір(?:и)?$/i, /^габарит(?:и|ні розміри)?$/i] }),
    volumeL: define("volumeL", { label: "Об’єм, л", type: "number", unit: "л", rank: 17, aliases: [/^об[’'`]?єм(?: бойлера| бака)?$/i, /^объем$/i, /^місткість$/i] }),
    weightKg: define("weightKg", { label: "Вага, кг", type: "number", unit: "кг", rank: 18, filterable: false, aliases: [/^вага(?:\s*\(кг\))?$/i, /^маса(?:\s*\(кг\))?$/i, /^weight$/i] }),
    filtrationMicron: define("filtrationMicron", { label: "Тонкість фільтрації, мкм", type: "number", unit: "мкм", rank: 19, aliases: [/^тонкість фільтрації$/i] }),
    pressureBar: define("pressureBar", { label: "Робочий тиск, бар", type: "number", unit: "бар", rank: 15, aliases: [/^робочий тиск$/i, /^макс\.?\s*тиск$/i, /^максимальний робочий тиск$/i, /^тиск максимальний$/i, /^давление$/i] }),
    diameter: define("diameter", { label: "Діаметр / DN", rank: 16, aliases: [/^dn$/i, /^діаметр$/i, /^диаметр$/i] }),
    connection: define("connection", { label: "Підключення", rank: 20, aliases: [/^підключення$/i, /^приєднання$/i, /^підключення котла$/i, /^підключення системи$/i, /^підключення контура? опалення$/i, /^підключення до контуру опалення$/i, /^підключення до колектора$/i, /^підключення контурів$/i, /^різьба(?: підключення)?$/i, /^з'єднання$/i] }),
    compatibility: define("compatibility", { label: "Сумісність", rank: 21, filterable: false, aliases: [/^сумісність$/i] }),
    protectionClass: define("protectionClass", { label: "Клас захисту", rank: 22, aliases: [/^клас захисту$/i, /^ступінь захисту$/i, /^ip$/i] }),
    outlets: define("outlets", { label: "Кількість виходів", rank: 18, aliases: [/^кількість виходів$/i, /^виходи$/i, /^кількість контурів$/i] }),
    material: define("material", { label: "Матеріал", rank: 19, aliases: [/^матеріал корпусу$/i, /^матеріал$/i, /^материал$/i] }),
    voltage: define("voltage", { label: "Живлення", rank: 20, aliases: [/^напруга$/i, /^живлення$/i, /^привід\s*\/\s*напруга$/i, /^напряжение$/i] }),
    control: define("control", { label: "Тип керування", rank: 21, aliases: [/^керування$/i, /^управління$/i, /^управление$/i, /^тип керування$/i] }),
    communication: define("communication", { label: "Спосіб зв’язку", rank: 21.1, aliases: [/^комунікація$/i, /^спосіб зв[’'`]язку$/i, /^тип зв[’'`]язку$/i, /^зв[’'`]язок$/i] }),
    zones: define("zones", { label: "Кількість зон", type: "number", rank: 21.2, aliases: [/^кількість зон$/i, /^зони$/i, /^кількість приміщень$/i] }),
    temperature: define("temperature", { label: "Температурний діапазон", rank: 22, aliases: [/^діапазон температур$/i, /^температура рідини$/i, /^макс\.?\s*температура$/i, /^максимальна температура$/i, /^температура$/i] }),
    eei: define("eei", { label: "Індекс енергоефективності EEI", rank: 22.1, aliases: [/^індекс енергетичної ефективності(?: \(eei\))?$/i, /^eei$/i] }),
    selfPriming: define("selfPriming", { label: "Самовсмоктування", rank: 22.2, aliases: [/^самовсмоктувальне виконання$/i] }),
    maxImmersionDepthM: define("maxImmersionDepthM", { label: "Максимальна глибина занурення, м", type: "number", unit: "м", rank: 22.3, aliases: [/^максимальна глибина занурення$/i] }),
    freePassageMm: define("freePassageMm", { label: "Вільний прохід, мм", type: "number", unit: "мм", rank: 22.4, aliases: [/^вільний сферичний прохід$/i, /^вільний прохід$/i] }),
    cableLengthM: define("cableLengthM", { label: "Довжина кабелю, м", type: "number", unit: "м", rank: 22.5, aliases: [/^довжина кабелю$/i] }),
    floatSwitch: define("floatSwitch", { label: "Поплавковий вимикач", rank: 22.6, aliases: [/^поплавковий вимикач$/i] }),
    waterType: define("waterType", { label: "Тип води", rank: 23, aliases: [/^вода$/i, /^тип води$/i] }),
    format: define("format", { label: "Формат / типорозмір", rank: 24, aliases: [/^формат$/i, /^типорозмір$/i] }),
    pump: define("pump", { label: "Помпа", rank: 25, aliases: [/^помпа$/i, /^насос підвищення тиску$/i] }),
    mineralizer: define("mineralizer", { label: "Мінералізація", rank: 26, aliases: [/^мінералізація$/i, /^мінералізатор$/i] }),
    flowType: define("flowType", { label: "Тип системи", rank: 27, aliases: [/^тип системи$/i, /^формат системи$/i] }),
    scope: define("scope", { label: "Для об’єкта", rank: 28, aliases: [/^для об'єкта$/i, /^сфера застосування$/i] })
  });

  const valueLabels = Object.freeze({
    yes: "Так",
    no: "Ні",
    direct: "Прямоточна",
    tank: "З баком",
    apartment: "Квартира",
    house: "Будинок",
    business: "Бізнес / HoReCa",
    mains: "Водогін",
    borehole: "Свердловина",
    "under-sink": "Під мийку",
    mechanical: "Механічне очищення",
    softening: "Пом’якшення",
    "iron-removal": "Знезалізнення",
    "chlorine-odor": "Хлор і запахи",
    complex: "Комплексне очищення"
  });

  const cardPriorityByCategory = Object.freeze({
    "circulation-pumps": Object.freeze(["headM", "flowM3h", "mountingLengthMm", "connection", "diameter", "powerKw"]),
    "underfloor-heating": Object.freeze(["diameter", "connection", "material", "pressureBar", "temperature", "outlets"]),
    "distribution-hydraulics": Object.freeze(["flowM3h", "heatOutputKw", "outlets", "connection", "diameter", "pressureBar", "mountingLengthMm"]),
    automation: Object.freeze(["productType", "control", "communication", "zones", "installation", "voltage"]),
    valves: Object.freeze(["diameter", "connection", "kvs", "pressureBar", "control", "material", "temperature"]),
    "heating-components": Object.freeze(["productType", "compatibility", "communication", "installation", "voltage", "protectionClass"]),
    "reverse-osmosis": Object.freeze(["capacityLh", "pump", "mineralizer", "flowType", "installation", "technology"]),
    "drinking-system-cartridges": Object.freeze(["purpose", "type", "filtrationMicron", "compatibility", "mineralizer"]),
    "mainline-cartridges": Object.freeze(["purpose", "type", "filtrationMicron", "format", "compatibility"]),
    "mainline-filters-housings": Object.freeze(["connection", "waterType", "purpose", "scope"]),
    "filter-media": Object.freeze(["purpose", "type", "waterSource"]),
    "complex-treatment": Object.freeze(["purpose", "flowM3h", "waterSource", "installation", "scope", "technology"]),
    "water-softening": Object.freeze(["purpose", "flowM3h", "waterSource", "installation", "scope"]),
    "mechanical-treatment": Object.freeze(["purpose", "flowM3h", "waterSource", "installation", "scope"]),
    "chlorine-odor-removal": Object.freeze(["purpose", "flowM3h", "waterSource", "installation", "scope"]),
    "flow-filters": Object.freeze(["type", "purpose", "installation", "filtrationMicron"]),
    "multistage-pumps": Object.freeze(["powerKw", "selfPriming", "connection", "pressureBar", "voltage", "protectionClass"]),
    "drainage-pumps": Object.freeze(["powerKw", "freePassageMm", "maxImmersionDepthM", "floatSwitch", "connection", "protectionClass"]),
    "borehole-pumps": Object.freeze(["headM", "flowM3h", "powerKw", "connection", "voltage", "protectionClass"]),
    "surface-pumps": Object.freeze(["headM", "flowM3h", "powerKw", "selfPriming", "connection", "pressureBar"]),
    "pressure-boosting": Object.freeze(["headM", "flowM3h", "powerKw", "pressureBar", "connection", "control"]),
    "sewage-pumps": Object.freeze(["headM", "flowM3h", "powerKw", "freePassageMm", "connection", "protectionClass"]),
    "sewage-lifting-units": Object.freeze(["headM", "flowM3h", "powerKw", "volumeL", "connection", "control"]),
    "pressure-tanks": Object.freeze(["volumeL", "pressureBar", "connection", "material", "installation", "temperature"]),
    "pump-automation": Object.freeze(["pressureBar", "connection", "voltage", "protectionClass", "control", "temperature"]),
    "pump-accessories": Object.freeze(["compatibility", "connection", "material", "pressureBar", "weightKg"]),
    "pump-services": Object.freeze(["productType", "compatibility"]),
    "pool-pumps-filtration": Object.freeze(["flowM3h", "headM", "powerKw", "connection", "voltage", "protectionClass", "filtrationMicron"]),
    "feed-grinders": Object.freeze(["powerKw", "capacityKgh", "rotationRpm", "voltage", "protectionClass", "weightKg"]),
    "solid-fuel-boilers": Object.freeze(["heatOutputKw", "fuel", "efficiencyPercent", "fireboxVolumeL", "waterVolumeL", "chimneyDiameterMm"]),
    "pellet-boilers": Object.freeze(["heatOutputKw", "fuel", "efficiencyPercent", "waterVolumeL", "chimneyDiameterMm", "consumptionPowerW"]),
    "heat-accumulators": Object.freeze(["volumeL", "pressureBar", "connection", "heightMm", "widthMm", "weightKg"]),
    "pellet-burners": Object.freeze(["heatOutputKw", "fuel", "consumptionPowerW", "voltage", "compatibility", "weightKg"]),
    "boiler-accessories": Object.freeze(["productType", "compatibility", "volumeL", "heatOutputKw", "connection", "weightKg"]),
    "industrial-heating": Object.freeze(["heatOutputKw", "capacityKgh", "fuel", "efficiencyPercent", "consumptionPowerW", "pressureBar"]),
    humidification: Object.freeze(["productType", "purpose", "flowM3h", "pressureBar", "voltage", "powerKw"])
  });

  const cardFallbackPriority = Object.freeze([
    "purpose", "type", "technology", "capacityLh", "flowM3h", "headM", "kvs", "powerKw", "heatOutputKw",
    "connection", "diameter", "diameterMm", "mountingLengthMm", "pressureBar", "filtrationMicron", "material",
    "control", "communication", "zones", "voltage", "protectionClass", "compatibility", "waterSource", "installation", "format", "pump",
    "mineralizer", "flowType", "scope", "volumeL", "weightKg", "capacityKgh", "rotationRpm", "widthMm", "heightMm", "depthMm", "dimensions", "eei", "selfPriming", "maxImmersionDepthM", "freePassageMm", "cableLengthM", "floatSwitch", "productType"
  ]);

  const pdpPriorityByCategory = Object.freeze({
    "circulation-pumps": Object.freeze(["headM", "flowM3h", "mountingLengthMm", "connection", "powerKw", "control"]),
    "underfloor-heating": Object.freeze(["diameter", "connection", "outlets", "material", "pressureBar", "temperature"]),
    "distribution-hydraulics": Object.freeze(["flowM3h", "heatOutputKw", "outlets", "connection", "diameter", "pressureBar"]),
    automation: Object.freeze(["productType", "control", "communication", "zones", "installation", "voltage", "protectionClass", "temperature"]),
    valves: Object.freeze(["diameter", "kvs", "pressureBar", "connection", "material", "control"]),
    "heating-components": Object.freeze(["productType", "compatibility", "communication", "installation", "voltage", "protectionClass"]),
    "reverse-osmosis": Object.freeze(["capacityLh", "pump", "mineralizer", "flowType", "installation", "technology"]),
    "drinking-system-cartridges": Object.freeze(["type", "purpose", "compatibility", "filtrationMicron", "mineralizer"]),
    "mainline-cartridges": Object.freeze(["filtrationMicron", "format", "type", "purpose", "compatibility"]),
    "mainline-filters-housings": Object.freeze(["connection", "format", "waterType", "purpose", "scope"]),
    "filter-media": Object.freeze(["type", "purpose", "waterSource", "format"]),
    "complex-treatment": Object.freeze(["flowM3h", "purpose", "waterSource", "installation", "scope", "technology"]),
    "water-softening": Object.freeze(["flowM3h", "purpose", "waterSource", "installation", "scope"]),
    "mechanical-treatment": Object.freeze(["flowM3h", "purpose", "waterSource", "installation", "scope"]),
    "chlorine-odor-removal": Object.freeze(["flowM3h", "purpose", "waterSource", "installation", "scope"]),
    "flow-filters": Object.freeze(["type", "purpose", "installation", "filtrationMicron", "flowM3h"]),
    "multistage-pumps": Object.freeze(["powerKw", "pressureBar", "selfPriming", "connection", "voltage", "protectionClass"]),
    "drainage-pumps": Object.freeze(["powerKw", "freePassageMm", "maxImmersionDepthM", "cableLengthM", "floatSwitch", "connection"]),
    "borehole-pumps": Object.freeze(["headM", "flowM3h", "powerKw", "connection", "voltage", "protectionClass"]),
    "surface-pumps": Object.freeze(["headM", "flowM3h", "powerKw", "selfPriming", "connection", "pressureBar"]),
    "pressure-boosting": Object.freeze(["headM", "flowM3h", "powerKw", "pressureBar", "connection", "control"]),
    "sewage-pumps": Object.freeze(["headM", "flowM3h", "powerKw", "freePassageMm", "maxImmersionDepthM", "connection"]),
    "sewage-lifting-units": Object.freeze(["headM", "flowM3h", "powerKw", "volumeL", "connection", "control"]),
    "pressure-tanks": Object.freeze(["volumeL", "pressureBar", "connection", "material", "installation", "temperature"]),
    "pump-automation": Object.freeze(["pressureBar", "connection", "voltage", "protectionClass", "control", "temperature"]),
    "pump-accessories": Object.freeze(["compatibility", "connection", "material", "pressureBar", "weightKg"]),
    "pump-services": Object.freeze(["productType", "compatibility"]),
    "pool-pumps-filtration": Object.freeze(["flowM3h", "headM", "powerKw", "connection", "voltage", "protectionClass", "filtrationMicron"]),
    "feed-grinders": Object.freeze(["powerKw", "capacityKgh", "rotationRpm", "voltage", "protectionClass", "weightKg"]),
    "solid-fuel-boilers": Object.freeze(["heatOutputKw", "fuel", "efficiencyPercent", "fireboxVolumeL", "waterVolumeL", "pressureBar", "maxWaterTemperatureC", "chimneyDiameterMm", "chimneyHeightM", "weightKg"]),
    "pellet-boilers": Object.freeze(["heatOutputKw", "fuel", "efficiencyPercent", "waterVolumeL", "pressureBar", "maxWaterTemperatureC", "chimneyDiameterMm", "consumptionPowerW", "weightKg"]),
    "heat-accumulators": Object.freeze(["volumeL", "pressureBar", "connection", "material", "temperature", "heightMm", "widthMm", "weightKg"]),
    "pellet-burners": Object.freeze(["heatOutputKw", "fuel", "consumptionPowerW", "voltage", "compatibility", "weightKg"]),
    "boiler-accessories": Object.freeze(["productType", "compatibility", "volumeL", "heatOutputKw", "connection", "material", "consumptionPowerW", "weightKg"]),
    "industrial-heating": Object.freeze(["heatOutputKw", "capacityKgh", "fuel", "efficiencyPercent", "consumptionPowerW", "pressureBar", "weightKg"]),
    humidification: Object.freeze(["productType", "purpose", "flowM3h", "pressureBar", "voltage", "powerKw", "connection"])
  });

  const pdpFallbackPriority = Object.freeze([
    ...cardFallbackPriority,
    "outlets", "widthMm", "heightMm", "depthMm", "dimensions", "volumeL", "weightKg"
  ]);

  const cardAttributeLabels = Object.freeze({
    capacityLh: "Продуктивність",
    capacityKgh: "Продуктивність",
    rotationRpm: "Оберти",
    flowM3h: "Подача",
    headM: "Макс. напір",
    powerKw: "Потужність",
    heatOutputKw: "Теплова потужність",
    fuel: "Паливо",
    efficiencyPercent: "ККД",
    waterVolumeL: "Водяна ємність",
    fireboxVolumeL: "Об’єм топки",
    chimneyDiameterMm: "Діаметр димоходу",
    chimneyHeightM: "Висота димоходу",
    consumptionPowerW: "Споживання",
    maxWaterTemperatureC: "Макс. температура води",
    mountingLengthMm: "Монтажна довжина",
    filtrationMicron: "Фільтрація",
    pressureBar: "Робочий тиск",
    diameter: "Діаметр / DN",
    diameterMm: "Діаметр",
    connection: "Підключення",
    protectionClass: "Клас захисту",
    outlets: "Кількість виходів",
    voltage: "Живлення",
    control: "Керування",
    communication: "Зв’язок",
    zones: "Кількість зон",
    temperature: "Температура",
    eei: "EEI",
    selfPriming: "Самовсмоктування",
    maxImmersionDepthM: "Глибина занурення",
    freePassageMm: "Вільний прохід",
    cableLengthM: "Довжина кабелю",
    floatSwitch: "Поплавок",
    waterSource: "Джерело води",
    productType: "Тип обладнання"
  });

  const seriesLabels = Object.freeze({
    "termojet-mega": "Mega",
    "termojet-box": "Box",
    "wilo-yonos-pico1-0": "Yonos PICO1.0",
    "wilo-star-z-nova": "Star-Z NOVA",
    "wilo-himulti-3": "HiMulti 3",
    "wilo-drain-tm-32": "Drain TM/TMW/TMR 32",
    "wilo-stratos-maxo": "Stratos MAXO",
    ...(window.sofievkaWiloSeriesLabels || {}),
    ...(window.sofievkaGrundfosSeriesLabels || {}),
    ...(window.sofievkaTekkhausSeriesLabels || {}),
    ...(window.sofievkaTechSeriesLabels || {}),
    ...(window.sofievkaHeatingBrandsSeriesLabels || {})
  });

  window.sofievkaAttributeSchema = Object.freeze({ definitions, valueLabels, cardPriorityByCategory, cardFallbackPriority, pdpPriorityByCategory, pdpFallbackPriority, cardAttributeLabels, seriesLabels });
})();
