(function () {
  "use strict";

  const category = config => ({
    status: "active",
    visibility: "catalog",
    menuDescription: "",
    allowedFacetIds: [],
    seo: {},
    ...config
  });

  const pumpFacets = ["productType", "type", "headM", "flowM3h", "powerKw", "connection", "pressureBar", "voltage", "protectionClass", "control"];
  const boilerFacets = ["productType", "type", "heatOutputKw", "fuel", "efficiencyPercent", "waterVolumeL", "pressureBar", "maxWaterTemperatureC", "chimneyDiameterMm", "weightKg"];
  const automationFacets = ["productType", "type", "control", "communication", "zones", "installation", "voltage", "protectionClass", "temperature"];
  const hydraulicFacets = ["productType", "type", "outlets", "connection", "flowM3h", "heatOutputKw", "material", "pressureBar"];
  const accessoryFacets = ["productType", "type", "compatibility", "connection", "material", "voltage", "consumptionPowerW", "weightKg"];
  const treatmentFacets = ["productType", "purpose", "waterSource", "technology", "installation", "capacityLh", "waterType", "format", "pump", "mineralizer", "flowType", "scope"];

  const definitions = [
    category({ id: "heating", slug: "heating", parentId: null, level: 1, title: "Опалення", shortTitle: "Опалення", description: "Обладнання для генерації, розподілу й керування теплом у житлових, комерційних та промислових системах.", menuDescription: "Котли, теплові насоси, гідравліка та автоматика", order: 10, seo: { title: "Опалення | ТД «Софіївка»", description: "Котли, теплові насоси, гідравліка, автоматика та комплектуючі для систем опалення." } }),
    category({ id: "water-supply", slug: "water-supply", parentId: null, level: 1, title: "Водопостачання та каналізація", shortTitle: "Вода й каналізація", description: "Насоси, установки, баки, автоматика та комплектуючі для подачі й відведення води.", menuDescription: "Насоси, каналізаційні установки, баки й автоматика", order: 20, seo: { title: "Водопостачання та каналізація | ТД «Софіївка»", description: "Насоси та обладнання для водопостачання, підвищення тиску й каналізації." } }),
    category({ id: "water-treatment", slug: "water-treatment", parentId: null, level: 1, title: "Водоочищення", shortTitle: "Водоочищення", description: "Питні фільтри, системи очищення всього будинку, картриджі, матеріали та UV-C знезараження.", menuDescription: "Фільтри, осмос, пом’якшення, картриджі та UV-C", order: 30, allowedFacetIds: treatmentFacets, seo: { title: "Водоочищення | ТД «Софіївка»", description: "Системи водоочищення, питні фільтри, картриджі, матеріали й UV-C знезараження." } }),
    category({ id: "smart-home", slug: "smart-home", parentId: null, level: 1, title: "Розумний будинок і автоматизація", shortTitle: "Розумний будинок", description: "Центральні блоки, освітлення, реле, датчики, захист від протікання та керування кліматом.", menuDescription: "Sinum, освітлення, реле, датчики та клімат", order: 40, seo: { title: "Розумний будинок і автоматизація | ТД «Софіївка»", description: "Компоненти TECH Sinum для автоматизації будинку, освітлення, клімату та безпеки." } }),
    category({ id: "climate", slug: "climate", parentId: null, level: 1, title: "Клімат", shortTitle: "Клімат", description: "Кондиціонери та системи туманоутворення для охолодження й зволоження повітря.", menuDescription: "Кондиціонери та туманоутворення", order: 50, seo: { title: "Кліматичне обладнання | ТД «Софіївка»", description: "Кондиціонери та системи туманоутворення для житлових і комерційних об’єктів." } }),
    category({ id: "household-equipment", slug: "household-equipment", parentId: null, level: 1, title: "Обладнання для господарства", shortTitle: "Для господарства", description: "Електричне обладнання для підготовки кормів та повсякденних господарських задач.", menuDescription: "Подрібнення та підготовка кормів", order: 60, seo: { title: "Обладнання для господарства | ТД «Софіївка»", description: "Електричне обладнання для приватного та фермерського господарства." } }),
    category({ id: "plumbing", slug: "plumbing", parentId: null, level: 1, title: "Сантехніка", shortTitle: "Сантехніка", description: "Напрям готується до наповнення перевіреним асортиментом.", menuDescription: "Рішення під замовлення", order: 70, status: "future", visibility: "landing", seo: { title: "Сантехніка | ТД «Софіївка»", description: "Сантехнічні рішення під замовлення з підбором і комплектацією." } }),

    category({ id: "heat-generation", slug: "heat-generation", parentId: "heating", level: 2, title: "Теплогенерація", shortTitle: "Теплогенерація", description: "Котли, пальники, теплогенератори та парогенератори за типом палива й призначенням.", order: 110 }),
    category({ id: "gas-boilers", slug: "gas-boilers", parentId: "heat-generation", level: 3, title: "Газові котли", shortTitle: "Газові котли", description: "Побутові, комерційні та промислові газові котли.", order: 111, allowedFacetIds: ["productType", "type", "heatOutputKw", "efficiencyPercent", "dhwFlowLMin", "installation", "energyClass", "dimensions", "weightKg", "voltage", "protectionClass"] }),
    category({ id: "solid-fuel-boilers", slug: "solid-fuel-boilers", parentId: "heat-generation", level: 3, title: "Твердопаливні котли", shortTitle: "Твердопаливні котли", description: "Котли з ручним завантаженням дров, вугілля та брикетів.", order: 112, allowedFacetIds: boilerFacets }),
    category({ id: "pellet-boilers", slug: "pellet-boilers", parentId: "heat-generation", level: 3, title: "Пелетні котли й мінікотельні", shortTitle: "Пелетні котли", description: "Автоматизовані пелетні котли та готові мінікотельні.", order: 113, allowedFacetIds: boilerFacets }),
    category({ id: "pellet-burners", slug: "pellet-burners", parentId: "heat-generation", level: 3, title: "Пелетні пальники", shortTitle: "Пелетні пальники", description: "Пелетні пальники для модернізації сумісного котельного обладнання.", order: 114, allowedFacetIds: accessoryFacets }),
    category({ id: "heat-generators", slug: "heat-generators", parentId: "heat-generation", level: 3, title: "Теплогенератори", shortTitle: "Теплогенератори", description: "Промислові повітряні теплогенератори для обігріву великих приміщень.", order: 115, allowedFacetIds: boilerFacets }),
    category({ id: "steam-generators", slug: "steam-generators", parentId: "heat-generation", level: 3, title: "Парогенератори", shortTitle: "Парогенератори", description: "Пелетні парогенератори для технологічних і промислових задач.", order: 116, allowedFacetIds: ["productType", "heatOutputKw", "fuel", "capacityKgh", "efficiencyPercent", "consumptionPowerW", "pressureBar", "weightKg"] }),

    category({ id: "heat-pumps", slug: "heat-pumps", parentId: "heating", level: 2, title: "Теплові насоси", shortTitle: "Теплові насоси", description: "Повітряні та геотермальні теплові насоси для опалення, охолодження й ГВП.", order: 120, allowedFacetIds: ["productType", "heatOutputKw", "coolingCapacityKw", "refrigerant", "cop", "scop", "energyClass", "voltage", "soundLevelDb", "maxWaterTemperatureC", "dimensions", "weightKg"] }),
    category({ id: "hot-water-storage", slug: "hot-water-storage", parentId: "heating", level: 2, title: "Гаряча вода й акумулювання", shortTitle: "ГВП і акумулювання", description: "Бойлери непрямого нагріву та буферні ємності.", order: 130 }),
    category({ id: "hot-water-tanks", slug: "hot-water-tanks", parentId: "hot-water-storage", level: 3, title: "Бойлери непрямого нагріву", shortTitle: "Бойлери", description: "Баки й бойлери для накопичення та приготування гарячої води.", order: 131, allowedFacetIds: ["productType", "volumeL", "heatOutputKw", "pressureBar", "maxWaterTemperatureC", "connection", "material", "installation", "dimensions", "weightKg", "compatibility"] }),
    category({ id: "heat-accumulators", slug: "heat-accumulators", parentId: "hot-water-storage", level: 3, title: "Буферні ємності й теплоакумулятори", shortTitle: "Теплоакумулятори", description: "Буферні ємності для акумулювання тепла та стабілізації системи.", order: 132, allowedFacetIds: ["productType", "volumeL", "pressureBar", "connection", "material", "temperature", "widthMm", "heightMm", "weightKg"] }),

    category({ id: "circulation-pumps", slug: "circulation-pumps", parentId: "heating", level: 2, title: "Насоси опалення", shortTitle: "Насоси опалення", description: "Циркуляційні насоси для опалення та рециркуляції гарячої води.", order: 140, allowedFacetIds: pumpFacets }),
    category({ id: "system-circulation-pumps", slug: "system-circulation", parentId: "circulation-pumps", level: 3, title: "Системні циркуляційні насоси", shortTitle: "Системна циркуляція", description: "Насоси для котлових, радіаторних, змішувальних та інших опалювальних контурів.", order: 141, allowedFacetIds: pumpFacets }),
    category({ id: "dhw-circulation-pumps", slug: "dhw-recirculation", parentId: "circulation-pumps", level: 3, title: "Насоси рециркуляції ГВП", shortTitle: "Рециркуляція ГВП", description: "Компактні насоси для контурів рециркуляції гарячої води.", order: 142, allowedFacetIds: pumpFacets }),

    category({ id: "distribution-hydraulics", slug: "distribution-hydraulics", parentId: "heating", level: 2, title: "Гідравліка та розподіл", shortTitle: "Гідравліка", description: "Насосні групи, колектори, гідравлічні роздільники, сепаратори й арматура.", order: 150, allowedFacetIds: hydraulicFacets }),
    category({ id: "pump-groups", slug: "pump-groups", parentId: "distribution-hydraulics", level: 3, title: "Насосні групи", shortTitle: "Насосні групи", description: "Готові модулі циркуляції та змішування для котельних контурів.", order: 151, allowedFacetIds: hydraulicFacets }),
    category({ id: "distribution-manifolds", slug: "distribution-manifolds", parentId: "distribution-hydraulics", level: 3, title: "Розподільчі колектори", shortTitle: "Колектори", description: "Колектори для розподілу теплоносія між контурами.", order: 152, allowedFacetIds: hydraulicFacets }),
    category({ id: "manifolds-with-hydraulic-separator", slug: "manifolds-with-separator", parentId: "distribution-hydraulics", level: 3, title: "Колектори з гідророздільником", shortTitle: "Колектори з гідрострілкою", description: "Комбіновані колектори з вбудованим гідравлічним розділенням.", order: 153, allowedFacetIds: hydraulicFacets }),
    category({ id: "hydraulic-separators", slug: "hydraulic-separators", parentId: "distribution-hydraulics", level: 3, title: "Гідравлічні роздільники", shortTitle: "Гідророздільники", description: "Гідрострілки та вузли гідравлічного розділення контурів.", order: 154, allowedFacetIds: hydraulicFacets }),
    category({ id: "air-dirt-separators", slug: "air-dirt-separators", parentId: "distribution-hydraulics", level: 3, title: "Сепаратори повітря та бруду", shortTitle: "Сепаратори", description: "Сепаратори для видалення повітря, шламу та магнітних домішок.", order: 155, allowedFacetIds: hydraulicFacets }),
    category({ id: "heating-valves", slug: "valves", parentId: "distribution-hydraulics", level: 3, title: "Змішувальна й балансувальна арматура", shortTitle: "Арматура", description: "Клапани, приводи та балансувальна арматура для гідравлічних контурів.", order: 156, allowedFacetIds: hydraulicFacets }),

    category({ id: "underfloor-heating", slug: "underfloor-heating", parentId: "heating", level: 2, title: "Тепла підлога", shortTitle: "Тепла підлога", description: "Колектори та вузли розподілу контурів водяної теплої підлоги.", order: 160, allowedFacetIds: ["productType", "outlets", "connection", "material", "pressureBar"] }),
    category({ id: "automation", slug: "automation", parentId: "heating", level: 2, title: "Автоматика опалення", shortTitle: "Автоматика опалення", description: "Термостати, контролери, зональне керування, датчики та комунікаційні модулі для систем опалення.", order: 170, allowedFacetIds: automationFacets }),
    category({ id: "room-thermostats", slug: "room-thermostats", parentId: "automation", level: 3, title: "Кімнатні термостати й програматори", shortTitle: "Термостати", description: "Кімнатне керування температурою, розкладом і режимами опалення.", order: 171, allowedFacetIds: automationFacets }),
    category({ id: "heating-controllers", slug: "system-controllers", parentId: "automation", level: 3, title: "Контролери котлів і систем", shortTitle: "Контролери", description: "Контролери котлів, насосів, клапанів і комплексних систем опалення.", order: 172, allowedFacetIds: automationFacets }),
    category({ id: "zone-control", slug: "zone-control", parentId: "automation", level: 3, title: "Зональне керування й приводи", shortTitle: "Зональне керування", description: "Контролери зон, термостатичні приводи та модулі теплої підлоги.", order: 173, allowedFacetIds: automationFacets }),
    category({ id: "heating-sensors-modules", slug: "sensors-modules", parentId: "automation", level: 3, title: "Датчики та комунікаційні модулі", shortTitle: "Датчики й модулі", description: "Датчики, ретранслятори, мережеві модулі та допоміжні компоненти автоматики.", order: 174, allowedFacetIds: automationFacets }),

    category({ id: "solar-thermal", slug: "solar-thermal", parentId: "heating", level: 2, title: "Сонячна теплова енергія", shortTitle: "Геліосистеми", description: "Сонячні колектори, баки та компоненти геліосистем.", order: 180, allowedFacetIds: ["productType", "collectorAreaM2", "installation", "pressureBar", "maxWaterTemperatureC", "dimensions", "weightKg", "compatibility"] }),
    category({ id: "flue-systems", slug: "flue-systems", parentId: "heating", level: 2, title: "Димоходи для котлів", shortTitle: "Димоходи", description: "Коаксіальні, роздільні та каскадні системи димовидалення.", order: 190, allowedFacetIds: accessoryFacets }),
    category({ id: "heating-components", slug: "heating-components", parentId: "heating", level: 2, title: "Комплектуючі для котлів і опалення", shortTitle: "Комплектуючі", description: "Монтажні, сервісні та фірмові компоненти котельного обладнання.", order: 200, allowedFacetIds: accessoryFacets }),
    category({ id: "boiler-doors-grates", slug: "doors-grates", parentId: "heating-components", level: 3, title: "Двері, рами та колосники", shortTitle: "Двері й колосники", description: "Двері, лутки, рами, колосники та зачепи для котлів.", order: 201, allowedFacetIds: accessoryFacets }),
    category({ id: "pellet-hoppers-augers", slug: "hoppers-augers", parentId: "heating-components", level: 3, title: "Бункери та шнекова подача", shortTitle: "Бункери й шнеки", description: "Пелетні бункери, шнеки та компоненти систем подачі палива.", order: 202, allowedFacetIds: accessoryFacets }),
    category({ id: "boiler-fans", slug: "boiler-fans", parentId: "heating-components", level: 3, title: "Вентилятори для котлів", shortTitle: "Вентилятори", description: "Наддувні та витяжні вентилятори котельного обладнання.", order: 203, allowedFacetIds: accessoryFacets }),
    category({ id: "boiler-cleaning-systems", slug: "cleaning-systems", parentId: "heating-components", level: 3, title: "Системи очищення котлів", shortTitle: "Очищення котлів", description: "Пневматичні та інші системи автоматичного очищення.", order: 204, allowedFacetIds: accessoryFacets }),
    category({ id: "boiler-hydraulic-nodes", slug: "boiler-hydraulic-nodes", parentId: "heating-components", level: 3, title: "Гідравлічні вузли котелень", shortTitle: "Гідровузли", description: "Гідравлічні модулі та вузли обв’язки котельного обладнання.", order: 205, allowedFacetIds: accessoryFacets }),
    category({ id: "heating-fittings", slug: "fittings-adapters", parentId: "heating-components", level: 3, title: "Муфти, переходи й адаптери", shortTitle: "Муфти й адаптери", description: "З’єднувальні елементи для колекторів, насосних груп і гідророздільників.", order: 206, allowedFacetIds: accessoryFacets }),
    category({ id: "branded-heating-accessories", slug: "brand-accessories", parentId: "heating-components", level: 3, title: "Інші фірмові комплектуючі", shortTitle: "Інші комплектуючі", description: "Інші підтверджені виробниками компоненти для монтажу, модернізації та сервісу.", order: 207, allowedFacetIds: accessoryFacets }),

    category({ id: "water-pumps", slug: "water-pumps", parentId: "water-supply", level: 2, title: "Насоси", shortTitle: "Насоси", description: "Насоси й комплектні установки за джерелом води та задачею.", order: 210 }),
    category({ id: "borehole-pumps", slug: "borehole-pumps", parentId: "water-pumps", level: 3, title: "Свердловинні насоси", shortTitle: "Свердловинні", description: "Занурювальні насоси й системи для свердловин та колодязів.", order: 211, allowedFacetIds: pumpFacets }),
    category({ id: "surface-pumps", slug: "surface-pumps", parentId: "water-pumps", level: 3, title: "Поверхневі насоси", shortTitle: "Поверхневі", description: "Поверхневі насоси для водопостачання, поливу й дощової води.", order: 212, allowedFacetIds: pumpFacets }),
    category({ id: "multistage-pumps", slug: "multistage-pumps", parentId: "water-pumps", level: 3, title: "Багатоступеневі насоси", shortTitle: "Багатоступеневі", description: "Горизонтальні багатоступеневі насоси для водопостачання та поливу.", order: 213, allowedFacetIds: pumpFacets }),
    category({ id: "pressure-boosting", slug: "pressure-boosting", parentId: "water-pumps", level: 3, title: "Підвищення тиску й насосні станції", shortTitle: "Підвищення тиску", description: "Насоси та установки для стабілізації тиску у водопостачанні.", order: 214, allowedFacetIds: pumpFacets }),
    category({ id: "drainage-pumps", slug: "drainage-pumps", parentId: "water-pumps", level: 3, title: "Дренажні насоси", shortTitle: "Дренажні", description: "Насоси для відведення дренажної та забрудненої води без фекалій.", order: 215, allowedFacetIds: pumpFacets }),
    category({ id: "sewage-pumps", slug: "sewage-pumps", parentId: "water-pumps", level: 3, title: "Каналізаційні та фекальні насоси", shortTitle: "Каналізаційні насоси", description: "Насоси для перекачування стічних і фекальних вод.", order: 216, allowedFacetIds: pumpFacets }),
    category({ id: "sewage-lifting-units", slug: "sewage-lifting-units", parentId: "water-pumps", level: 3, title: "Каналізаційні установки", shortTitle: "Каналізаційні установки", description: "Готові напірні установки для відведення стоків із санвузлів і будівель.", order: 217, allowedFacetIds: pumpFacets }),
    category({ id: "pool-pumps-filtration", slug: "pool-pumps-filtration", parentId: "water-pumps", level: 3, title: "Насоси та фільтрація для басейнів", shortTitle: "Для басейнів", description: "Насоси й фільтрувальні станції для приватних басейнів.", order: 218, allowedFacetIds: pumpFacets }),
    category({ id: "water-supply-components", slug: "components", parentId: "water-supply", level: 2, title: "Баки, автоматика й комплектуючі", shortTitle: "Комплектуючі", description: "Баки, контролери та монтажні компоненти насосного обладнання.", order: 220 }),
    category({ id: "pressure-tanks", slug: "pressure-tanks", parentId: "water-supply-components", level: 3, title: "Мембранні баки", shortTitle: "Мембранні баки", description: "Напірні мембранні баки для запасу води й стабілізації тиску.", order: 221, allowedFacetIds: ["productType", "volumeL", "pressureBar", "connection", "material", "installation", "temperature"] }),
    category({ id: "pump-automation", slug: "pump-automation", parentId: "water-supply-components", level: 3, title: "Автоматика насосів", shortTitle: "Автоматика насосів", description: "Контролери запуску, зупинки й захисту насосів.", order: 222, allowedFacetIds: automationFacets }),
    category({ id: "pump-accessories", slug: "pump-accessories", parentId: "water-supply-components", level: 3, title: "Монтажні комплектуючі для насосів", shortTitle: "Комплектуючі", description: "Клапани, колектори, кабелі, монтажні комплекти та інші компоненти.", order: 223, allowedFacetIds: accessoryFacets }),
    category({ id: "pump-services", slug: "pump-services", parentId: "water-supply-components", level: 3, title: "Пусконалагодження насосного обладнання", shortTitle: "Пусконалагодження", description: "Сервісна позиція, доступна через сервісний центр, а не товарну видачу.", order: 229, status: "internal", visibility: "service", allowedFacetIds: ["productType", "compatibility"] }),

    category({ id: "drinking-water-systems", slug: "drinking-water", parentId: "water-treatment", level: 2, title: "Питна вода", shortTitle: "Питна вода", description: "Системи під мийку для приготування питної води.", order: 310 }),
    category({ id: "reverse-osmosis", slug: "reverse-osmosis", parentId: "drinking-water-systems", level: 3, title: "Зворотний осмос", shortTitle: "Зворотний осмос", description: "Побутові та професійні системи зворотного осмосу.", order: 311, allowedFacetIds: treatmentFacets, legacyGroup: "drinking-water-systems", legacyGroupTitle: "Системи питної води" }),
    category({ id: "flow-filters", slug: "flow-filters", parentId: "drinking-water-systems", level: 3, title: "Проточні фільтри", shortTitle: "Проточні фільтри", description: "Проточні системи доочищення питної води.", order: 312, allowedFacetIds: treatmentFacets, legacyGroup: "drinking-water-systems", legacyGroupTitle: "Системи питної води" }),
    category({ id: "whole-house-treatment", slug: "whole-house", parentId: "water-treatment", level: 2, title: "Очищення води для будинку", shortTitle: "Для всього будинку", description: "Системи підготовки води на вході до будинку або комерційного об’єкта.", order: 320 }),
    category({ id: "complex-treatment", slug: "complex-treatment", parentId: "whole-house-treatment", level: 3, title: "Комплексне очищення", shortTitle: "Комплексне очищення", description: "Системи одночасного видалення кількох типів домішок.", order: 321, allowedFacetIds: treatmentFacets, legacyGroup: "whole-house-treatment", legacyGroupTitle: "Очищення води для будинку" }),
    category({ id: "water-softening", slug: "water-softening", parentId: "whole-house-treatment", level: 3, title: "Пом’якшення води", shortTitle: "Пом’якшення", description: "Системи зниження жорсткості води.", order: 322, allowedFacetIds: treatmentFacets, legacyGroup: "whole-house-treatment", legacyGroupTitle: "Очищення води для будинку" }),
    category({ id: "chlorine-odor-removal", slug: "chlorine-odor-removal", parentId: "whole-house-treatment", level: 3, title: "Видалення хлору та запаху", shortTitle: "Хлор і запах", description: "Системи видалення хлору, запахів і органічних домішок.", order: 323, allowedFacetIds: treatmentFacets, legacyGroup: "whole-house-treatment", legacyGroupTitle: "Очищення води для будинку" }),
    category({ id: "mechanical-treatment", slug: "mechanical-treatment", parentId: "whole-house-treatment", level: 3, title: "Механічне очищення", shortTitle: "Механічне очищення", description: "Системи попереднього очищення від піску, мулу та іржі.", order: 324, allowedFacetIds: treatmentFacets, legacyGroup: "whole-house-treatment", legacyGroupTitle: "Очищення води для будинку" }),
    category({ id: "mainline-filtration", slug: "mainline-filtration", parentId: "water-treatment", level: 2, title: "Магістральна фільтрація", shortTitle: "Магістральні фільтри", description: "Корпуси та картриджі для очищення води на вході.", order: 330 }),
    category({ id: "mainline-filters-housings", slug: "filter-housings", parentId: "mainline-filtration", level: 3, title: "Корпуси магістральних фільтрів", shortTitle: "Корпуси фільтрів", description: "Корпуси та готові магістральні фільтри.", order: 331, allowedFacetIds: treatmentFacets, legacyGroup: "whole-house-treatment", legacyGroupTitle: "Очищення води для будинку" }),
    category({ id: "mainline-cartridges", slug: "mainline-cartridges", parentId: "mainline-filtration", level: 3, title: "Картриджі магістральних фільтрів", shortTitle: "Магістральні картриджі", description: "Змінні картриджі для магістрального очищення води.", order: 332, allowedFacetIds: treatmentFacets, legacyGroup: "replacement-elements", legacyGroupTitle: "Змінні елементи" }),
    category({ id: "replacement-elements", slug: "replacement-elements", parentId: "water-treatment", level: 2, title: "Змінні елементи питних систем", shortTitle: "Змінні елементи", description: "Комплекти та окремі картриджі для питних систем.", order: 340 }),
    category({ id: "drinking-system-cartridges", slug: "drinking-system-cartridges", parentId: "replacement-elements", level: 3, title: "Картриджі питних систем", shortTitle: "Картриджі питних систем", description: "Змінні елементи для проточних фільтрів і систем зворотного осмосу.", order: 341, allowedFacetIds: treatmentFacets, legacyGroup: "replacement-elements", legacyGroupTitle: "Змінні елементи" }),
    category({ id: "materials-reagents", slug: "materials-reagents", parentId: "water-treatment", level: 2, title: "Завантаження та реагенти", shortTitle: "Матеріали", description: "Фільтрувальні завантаження й матеріали для систем очищення.", order: 350 }),
    category({ id: "filter-media", slug: "filter-media", parentId: "materials-reagents", level: 3, title: "Фільтрувальні матеріали", shortTitle: "Фільтрувальні матеріали", description: "Завантаження та матеріали для систем очищення води.", order: 351, allowedFacetIds: treatmentFacets, legacyGroup: "materials-reagents", legacyGroupTitle: "Матеріали та реагенти" }),
    category({ id: "water-disinfection", slug: "disinfection", parentId: "water-treatment", level: 2, title: "Знезараження води", shortTitle: "Знезараження", description: "Обладнання для безреагентного знезараження проточної води.", order: 360 }),
    category({ id: "uv-disinfection", slug: "uv-c-lamps", parentId: "water-disinfection", level: 3, title: "Проточні UV-C лампи", shortTitle: "UV-C лампи", description: "Проточні ультрафіолетові лампи для знезараження питної та побутової води.", order: 361, allowedFacetIds: ["productType", "flowM3h", "powerKw", "connection", "pressureBar", "voltage", "temperature"] }),

    category({ id: "smart-home-hubs", slug: "hubs-panels", parentId: "smart-home", level: 2, title: "Центральні блоки та панелі", shortTitle: "Блоки й панелі", description: "Головні контролери, панелі та інтерфейси системи Sinum.", order: 410, allowedFacetIds: automationFacets }),
    category({ id: "smart-lighting", slug: "lighting-switches", parentId: "smart-home", level: 2, title: "Освітлення, вимикачі й димери", shortTitle: "Освітлення", description: "Сенсорні вимикачі, димери й RGB-модулі керування освітленням.", order: 420, allowedFacetIds: automationFacets }),
    category({ id: "smart-shutters", slug: "shutters-blinds", parentId: "smart-home", level: 2, title: "Керування ролетами та жалюзі", shortTitle: "Ролети й жалюзі", description: "Вимикачі та модулі автоматизації ролет і жалюзі.", order: 430, allowedFacetIds: automationFacets }),
    category({ id: "smart-relays", slug: "relays-sockets", parentId: "smart-home", level: 2, title: "Реле, розетки та DIN-модулі", shortTitle: "Реле й розетки", description: "Силові реле, розетки, вхідні плати та модулі для щита.", order: 440, allowedFacetIds: automationFacets }),
    category({ id: "smart-sensors", slug: "sensors-security", parentId: "smart-home", level: 2, title: "Датчики, безпека та якість повітря", shortTitle: "Датчики й безпека", description: "Датчики диму, протікання, відкривання, руху та якості повітря.", order: 450, allowedFacetIds: automationFacets }),
    category({ id: "smart-climate", slug: "climate-control", parentId: "smart-home", level: 2, title: "Клімат і терморегуляція", shortTitle: "Клімат", description: "Терморегулятори, клапани та модулі кліматичного керування Sinum.", order: 460, allowedFacetIds: automationFacets }),
    category({ id: "smart-accessories", slug: "power-connectivity", parentId: "smart-home", level: 2, title: "Живлення, зв’язок і монтаж", shortTitle: "Живлення й монтаж", description: "Блоки живлення, кабелі, ретранслятори, рамки та монтажні аксесуари.", order: 470, allowedFacetIds: accessoryFacets }),

    category({ id: "air-conditioners", slug: "air-conditioners", parentId: "climate", level: 2, title: "Кондиціонери", shortTitle: "Кондиціонери", description: "Побутові спліт- і мультиспліт-системи для охолодження та обігріву.", order: 510, allowedFacetIds: ["productType", "coolingCapacityKw", "heatOutputKw", "refrigerant", "seer", "scop", "energyClass", "soundLevelDb", "voltage", "dimensions", "weightKg"] }),
    category({ id: "humidification", slug: "humidification", parentId: "climate", level: 2, title: "Туманоутворення та зволоження", shortTitle: "Туманоутворення", description: "Готові системи та комплектуючі для туманоутворення й охолодження повітря.", order: 520 }),
    category({ id: "misting-systems", slug: "systems", parentId: "humidification", level: 3, title: "Системи туманоутворення", shortTitle: "Готові системи", description: "Комплектні системи туманоутворення за кількістю форсунок.", order: 521, allowedFacetIds: pumpFacets }),
    category({ id: "misting-components", slug: "components", parentId: "humidification", level: 3, title: "Компоненти туманоутворення", shortTitle: "Компоненти", description: "Форсунки, трубки, з’єднання та монтажні компоненти систем.", order: 522, allowedFacetIds: accessoryFacets }),
    category({ id: "feed-grinders", slug: "feed-grinders", parentId: "household-equipment", level: 2, title: "Кормоподрібнювачі", shortTitle: "Кормоподрібнювачі", description: "Електричні подрібнювачі зернових культур і коренеплодів.", order: 610, allowedFacetIds: ["productType", "powerKw", "capacityKgh", "rotationRpm", "voltage", "protectionClass", "weightKg"] })
  ];

  const rawById = Object.fromEntries(definitions.map(item => [item.id, item]));
  const sectionIdFor = item => {
    let current = item;
    while (current?.parentId) current = rawById[current.parentId];
    return current?.id || "";
  };
  const nodes = Object.freeze(definitions.map(item => Object.freeze({
    ...item,
    name: item.title,
    metaTitle: item.seo?.title || `${item.title} | ТД «Софіївка»`,
    sectionId: sectionIdFor(item),
    facetIds: Object.freeze([...(item.allowedFacetIds || [])]),
    allowedFacetIds: Object.freeze([...(item.allowedFacetIds || [])]),
    seo: Object.freeze({ ...(item.seo || {}) })
  })));
  const byId = Object.freeze(Object.fromEntries(nodes.map(item => [item.id, item])));
  const childrenOf = parentId => nodes.filter(item => item.parentId === parentId).sort((a, b) => a.order - b.order);
  const descendantsOf = parentId => {
    const result = [];
    const visit = id => childrenOf(id).forEach(child => { result.push(child); visit(child.id); });
    visit(parentId);
    return result;
  };

  window.sofievkaTaxonomy = Object.freeze({
    nodes,
    byId,
    businessSections: Object.freeze(nodes.filter(item => item.level === 1).sort((a, b) => a.order - b.order)),
    productCategories: Object.freeze(nodes.filter(item => item.level > 1).sort((a, b) => a.order - b.order)),
    childrenOf,
    descendantsOf
  });
})();
